version: 2
updates:

  # ---------------------------
  # NodeJS (application-restricted API key tutorials)
  # ---------------------------
  - package-ecosystem: "npm"
    directory: "/application-restricted-api-key-tutorials"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels: [ "dependencies", "javascript", "api-key" ]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # ---------------------------
  # NodeJS (application-restricted signed JWT tutorials)
  # ---------------------------
  - package-ecosystem: "npm"
    directory: "/application-restricted-signed-jwt-tutorials"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels: [ "dependencies", "javascript", "signed-jwt" ]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # ---------------------------
  # NodeJS (user-restricted combined auth tutorials)
  # ---------------------------
  - package-ecosystem: "npm"
    directory: "/user-restricted-combined-auth-tutorials"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels: [ "dependencies", "javascript", "combined-auth" ]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # ---------------------------
  # NodeJS (user-restricted separate auth tutorials)
  # ---------------------------
  - package-ecosystem: "npm"
    directory: "/user-restricted-separate-auth-tutorials"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels: [ "dependencies", "javascript", "separate-auth" ]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # ---------------------------
  # GitHub Actions workflows
  # ---------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels: [ "dependencies", "github-actions" ]
    cooldown:
      default-days: 7
