name: SBOM Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sbom:
    uses: NHSDigital/api-management-utils/.github/workflows/shared-sbom-scan.yml@master
